# Generated by Django 4.1.7 on 2023-02-19 15:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название Игры')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='Индивидуальный ярлык')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(verbose_name='Доступен')),
                ('games_amount', models.IntegerField(default=0, verbose_name='Колличество игр')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название Игры')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='Индивидуальный ярлык')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(verbose_name='Доступен')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата Публикации')),
                ('release_date', models.DateField(verbose_name='Дата Выхода')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('game_image', models.ImageField(upload_to='game_store/media/games', verbose_name='Изображение Игры')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='game_store.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='game_store_category_name_index'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='game_store_game_name_index'),
        ),
    ]
