# Generated by Django 4.1.6 on 2023-02-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='games_amount',
            field=models.IntegerField(default=0, verbose_name='Колличество игр'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=25, verbose_name='Индивидуальный ярлык'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=25, verbose_name='Индивидуальный ярлык'),
        ),
    ]
