# Generated by Django 4.1.7 on 2023-02-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store', '0003_remove_category_title_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='games_amount',
            field=models.IntegerField(default=0, verbose_name='Колличество игр в категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=25, verbose_name='Индивидуальный ярлык'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=25, verbose_name='Индивидуальный ярлык'),
        ),
    ]
